# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('points', models.IntegerField(default=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('colour', models.CharField(choices=[('#FFB5B9', 'Red'), ('#FFE6BF', 'Orange'), ('#FFEDB5', 'Yellow'), ('#B5F2BA', 'Green'), ('#BFDAFF', 'Blue'), ('#DABFFF', 'Indigo'), ('#FBBFFF', 'Violet')], max_length=7, unique=True)),
                ('days', main.models.ListField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Subject'),
        ),
    ]
