# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161114_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='colour',
            field=models.CharField(choices=[('#FFB5B9', 'Red'), ('#FFE6BF', 'Orange'), ('#FFEDB5', 'Yellow'), ('#B5F2BA', 'Green'), ('#BFDAFF', 'Blue'), ('#DABFFF', 'Indigo'), ('#FBBFFF', 'Violet')], max_length=7),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
