# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-15 03:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyuser',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2016, 11, 15, 3, 27, 55, 881045, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyuser',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
    ]
